/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Sukuk, FAQItem } from './types';

export const curatedSukuk: Sukuk[] = [
  {
    id: 'sukuk-01',
    name: 'Sovereign Green Ijarah Sukuk',
    issuer: 'Republic Sukuk Commission (Sovereign)',
    type: 'Sovereign',
    yield: 5.20,
    tenure: '5 Years',
    structure: 'Ijarah',
    shariahCertifier: 'Aisha Shariah Supervisory Board (AAOIFI Standard)',
    minInvestment: 1000,
    rating: 'A+ Stable',
    frequency: 'Semi-Annual',
    underlyingAsset: 'Sovereign-Owned Public Solar & Wind Hydro Installations',
    aboutCheck: 'This Sukuk utilizes an Ijarah (leasing) structure. Physical renewable energy infrastructure assets are purchased and leased back to the sovereign utilities commission. The leasing payments generate regular, reliable profits distributed to you semi-annually, with no capital leverage in line with Shariah restrictions.',
    status: 'Available',
    riskLevel: 'Conservative'
  },
  {
    id: 'sukuk-02',
    name: 'Short-Term T-Sukuk Bill (Series A)',
    issuer: 'Federal Treasury Board',
    type: 'T-Sukuk',
    yield: 4.85,
    tenure: '3 Months',
    structure: 'Murabaha',
    shariahCertifier: 'Central Bank Shariah Board',
    minInvestment: 500,
    rating: 'AAA Sovereign',
    frequency: 'On Maturity',
    underlyingAsset: 'Government Purchase & Sale Commodity Reserves',
    aboutCheck: 'Designed for short-term liquidity and high safety. Under the Murabaha (cost-plus markup) structure, commodity inventories are purchased at spot prices and sold on deferred terms to state utilities, securing a set yield. This offers active secondary market sell-back flexibility through our licensed partner banks.',
    status: 'Available',
    riskLevel: 'Conservative'
  },
  {
    id: 'sukuk-03',
    name: 'Global Utility Wakalah Sukuk',
    issuer: 'Amana Infrastructure Corp',
    type: 'Corporate',
    yield: 6.50,
    tenure: '3 Years',
    structure: 'Wakalah',
    shariahCertifier: 'Dar Al Sharia Board (Dubai)',
    minInvestment: 2500,
    rating: 'AA- Investment Grade',
    frequency: 'Quarterly',
    underlyingAsset: 'Global Logistics & Fiber Optic Broadband Networks',
    aboutCheck: 'This Wakalah (agency) Sukuk assigns a Shariah-certified agent (Wakeel) to manage and optimize infrastructure lease contracts. The profit generated by these underlying physical telecommunications and logistics assets is returned as regular quarterly payments. Capital is secured against physical, non-speculative utility assets.',
    status: 'Available',
    riskLevel: 'Moderate'
  },
  {
    id: 'sukuk-04',
    name: 'Al-Barakah Diversified Sukuk Fund',
    issuer: 'Wafra Partners Mutual Fund Managers',
    type: 'Mutual Fund',
    yield: 5.45,
    tenure: 'Open-Ended',
    structure: 'Hybrid',
    shariahCertifier: 'International Shariah Scholars Board',
    minInvestment: 100,
    rating: 'A- Est.',
    frequency: 'Monthly',
    underlyingAsset: 'Diversified Basket of 40+ Sovereign and Corporate Sukuks',
    aboutCheck: 'An open-ended mutual fund giving you automatic exposure to a broad pool of international sovereign and corporate Sukuk. This fund utilizes a hybrid structure combining Mudharabah (partnership profits) and Wakalah principles. Ideal for retail investors seeking a monthly payout and automatic recurring buy options.',
    status: 'Available',
    riskLevel: 'Moderate'
  },
  {
    id: 'sukuk-05',
    name: 'Traded Coastal Port Expansion Sukuk',
    issuer: 'Maritime Logistics Authority',
    type: 'Corporate',
    yield: 5.90,
    tenure: '2 Years',
    structure: 'Ijarah',
    shariahCertifier: 'Amanah Shariah Scholars Board',
    minInvestment: 2000,
    rating: 'A Stable',
    frequency: 'Semi-Annual',
    underlyingAsset: 'Physical Deep-Water Docks & Cargo Crane Elevators',
    aboutCheck: 'This Sukuk is backed by concrete deep-water port expansions. All underlying assets are fully leased and commercialized. While subscriptions for the primary issuance are closed, our licensed secondary broker provides buy/sell trading volume and current market-quoted liquidity directly inside the partner broker client.',
    status: 'Secondary Market',
    riskLevel: 'Moderate'
  }
];

export const faqData: FAQItem[] = [
  {
    question: 'How does a Sukuk differ from a conventional interest-bearing bond?',
    answer: 'Unlike conventional bonds which are debt obligations paying interest (Riba), a Sukuk represents a fractional ownership in a real, tangible, income-generating asset. Profit is earned as direct rent or capital gains, which is fully permissible under Islamic Jurisprudence.',
    category: 'Shariah'
  },
  {
    question: 'Where is my money held and who executes my purchases?',
    answer: 'We are an information and access wrapper, NOT a broker or custodian. Your money remains protected inside your accounts with our integrated, licensed partner banks and brokers. They hold the Shariah securities in custody and execute your orders.',
    category: 'Security'
  },
  {
    question: 'What is the minimum investment requirement to get started?',
    answer: 'Our platform strives for maximum financial inclusion. While direct primary sovereign Sukuk typically require substantial minimums, our partner-managed Diversified Sukuk Fund lets you invest with as little as $100.',
    category: 'General'
  },
  {
    question: 'Can I sell my Sukuk before maturity if I need quick cash?',
    answer: 'Yes! T-Sukuk (short-term Sukuk) and corporate secondary market offerings can be sold back through our partner brokers. Trading volume is subject to secondary market liquidity and typical bid-ask spreads, with no penalty fees.',
    category: 'Liquidity'
  },
  {
    question: 'How do you verify the Shariah compliance of listed options?',
    answer: 'Every listed Sukuk includes a transparent breakdown of its underlying Shariah structure (e.g. Ijarah, Wakalah, Murabaha) and is accompanied by a downloadable Fatwa or certification from globally renowned scholars matching AAOIFI standard guidelines.',
    category: 'Shariah'
  },
  {
    question: 'Are there any hidden platform subscription or usage fees?',
    answer: 'Our directory and portfolio tracking features are 100% free for retail users. We receive standard routing administration support fees from partner banks and fund managers. No direct markup is ever added to your purchase price.',
    category: 'General'
  }
];
